# Generated by Django 4.0.3 on 2022-03-11 17:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='instructors')),
                ('phone', models.CharField(max_length=16)),
                ('zipcode', models.CharField(max_length=9)),
                ('authuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'InstrumentFamilies',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='whistlerapi.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MusicStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'MusicStyles',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Postions',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(17500.0)])),
                ('servicedate', models.DateField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whistlerapi.instrument')),
                ('musicstyle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whistlerapi.musicstyle')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbrev', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('is_active', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=16)),
                ('zipcode', models.CharField(max_length=9)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whistlerapi.state')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whistlerapi.invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whistlerapi.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='servicetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='whistlerapi.servicetype'),
        ),
        migrations.AddField(
            model_name='service',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='whistlerapi.shop'),
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_number', models.CharField(max_length=16)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_types', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_types', to='whistlerapi.merchant')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whistlerapi.paymenttype'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='services',
            field=models.ManyToManyField(related_name='invoices', through='whistlerapi.ServiceInvoice', to='whistlerapi.service'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whistlerapi.instrumentclass'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whistlerapi.position'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whistlerapi.shop'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whistlerapi.state'),
        ),
    ]
