# Generated by Django 4.0.3 on 2022-03-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whistlerapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='address2',
        ),
    ]
