# Generated by Django 4.0.3 on 2022-03-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whistlerapi', '0002_remove_shop_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='address2',
        ),
    ]
